language: erlang

matrix:
  include:
    - os: linux
      dist: xenial
      otp_release: 21.1
    - os: linux
      dist: xenial
      otp_release: 20.3.8.5
    - os: linux
      dist: xenial
      otp_release: 19.3
    - os: osx
      language: generic

before_script:

- if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get -y update || true ; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get install -y cmake cmake-curses-gui libgtest-dev libre2-dev libicu-dev  || true ; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get install -y libboost-dev libboost-thread-dev libboost-system-dev  || true ; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get install -y libprotobuf-dev protobuf-compiler  || true ; fi

- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then brew install erlang rebar3 || true; fi

script:
    - rebar3 compile

after_success:
  - rebar3 eunit
